name: "prod DEPLOY"

on:
  push:
    branches:
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::730335614976:role/github-actions-ddii596-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "ddii596-lab-terraform-statefile"
      aws-lock-dynamodb-table: "ddii596-lab-terraform-lock"